# External Access
{{- if .Values.postgresql.externalAccess.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.name }}-external
spec:
  type: {{ .Values.postgresql.externalAccess.service.type }}
  ports:
    - port: {{ .Values.postgresql.externalAccess.service.port }}
  selector:
    app.kubernetes.io/name: {{ .Values.postgresql.name }}
{{- end }}

# Backup Job
{{- if .Values.postgresql.backup.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.postgresql.name }}-backup
spec:
  schedule: "{{ .Values.postgresql.backup.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: bitnami/postgresql:latest
            command: ["sh", "-c", "pg_dump -U {{ .Values.postgresql.global.postgresql.auth.username }} -h {{ .Values.postgresql.name }} {{ .Values.postgresql.global.postgresql.auth.database }} > /backups/backup.sql"]
            env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: postgresql-password
            volumeMounts:
            - name: backup-volume
              mountPath: /backups
          restartPolicy: OnFailure
          volumes:
          - name: backup-volume
            persistentVolumeClaim:
              claimName: {{ .Values.postgresql.name }}-backup
{{- end }}