# External Access
{{- if .Values.redis.externalAccess.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.name }}-external
spec:
  type: {{ .Values.redis.externalAccess.service.type }}
  ports:
    - port: {{ .Values.redis.externalAccess.service.port }}
  selector:
    app.kubernetes.io/name: {{ .Values.redis.name }}
{{- end }}