apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
data:
  postgresql-password: {{ .Values.postgresql.global.postgresql.auth.password | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  redis-password: {{ .Values.redis.auth.password | b64enc }}
