# PostgreSQL configuration

postgresql:
  name: my-postgresql
  global:
    postgresql:
      auth:
        username: "myuser"
        database: "mydatabase"
        password: ""
  primary:
    persistence:
      enabled: true                       # Enable persistence
      storageClass: "standard"            # Specify the storage class (or leave empty for default)
      size: 10Gi                          # Size of the persistent storage
      accessModes:
        - ReadWriteOnce                   # Access mode for the volume
      annotations: {}                     # Any additional annotations for the PVC
      mountPath: /bitnami/postgresql      # Mount path where the PV will be attached
    resources:
      requests:
        memory: 256Mi
        cpu: 500m
  externalAccess:
    enabled: true
    service:
      type: LoadBalancer
      port: 5432
    autoDiscovery:
      enabled: true
  backup:
    enabled: true
    schedule: "0 2 * * *"
    retention: 10
    storage:
      persistentVolumeClaim:
        create: true
        size: 1Gi

# Redis configuration

redis:
  name: my-redis
  global:
    redis:
      password: ""
  architecture: standalone
  auth:
    enabled: true
    password: ""
  persistence:
    enabled: true
  externalAccess:
    enabled: true
    service:
      type: LoadBalancer
      port: 6379

# Simple app configuration
simpleApp:
  name: my-simple-app
  image:
    repository: nginx
    tag: latest
  service:
    type: ClusterIP
    port: 80
